language: java
jdk:
  - oraclejdk8
before_install:
  - nvm install 6.9.1
  - cd ./generator-spring
  - npm i -g makeshift && makeshift -r https://registry.npmjs.org
install:
  - npm install
script:
  - npm run lint
  - npm test
  - npm run testint
  - npm run coveralls
  - ../deploy.sh
  