language: java
jdk:
  - oraclejdk8
before_install:
  - nvm install 6.9.1
  - cd ./generator-spring
  - npm i -g makeshift && makeshift -r https://npm-registry.whitewater.ibm.com -s arf ibm wicked
install:
  - npm install
script:
  - npm test
  - npm run testint
  - npm run coverage
  - npm run coverageint
  - ../deploy.sh
env:
  - secure : "jCUer3jHOHsVc8CbFsQfwIsU4sjP0ZiYfpd1KlbM1nGJflF5jlFAJFsPhw9BsKa+g2kZXGUDcjJWWcfQybKu1JwYx0JvQpDpV2npT6E35P8i2WnIZb857BVfz0wBnt2JpBqaZMTxM8gzy33YOkRvTVjkYcZlkx5DrvOgmyLRjQJMZ5nIWRontpuP87x00Z5nY0jJAGBHvPxXB2vNhCdhMgjsIo4NHWaFFuiwwqj0cpy+wP4P7NO+U1mSLaCHg2o6RkAbyfKu1SyU+umdJ4b9e85gYoQp8fJ7k/cY/4slocIMIQD+uNCesRZeHgUlTC2X8tG+UKnfSIQh09mUTsAlF8t9+WHHo4zFIPhZ4VM+aoliLD7dvkFYl9NeWkBfxZbILb3ICC4lLZGXe+rRKYZyhmipAS6zyTC+2vwFckNynGk4N84JwO7a6fJGfUa0bTNVpZeR1KMUaTk/or/Mqz7vfHtWh/291T092NVu7L22UgIrwv9GVzKopbkRKxNx0uoZeFLmsJAfZ3bREpq6688+86oC5xjmQUdku52h9k5LeBe9oa7rC2o0NM6OW0pTxHx0qcJxT7R8W6qyt1rWKIBSncdFsG4wVX8kvTXKtyV6TDXbZ0jQDcHzK4jRowWnU8rlyNnT4iFPV3DhaaUZOo5U2H9EIUllrysrg0etZrq+NHM="
