language: java
jdk:
  - oraclejdk8
before_install:
  - nvm install 6.9.1
  - cd ./generator-spring
  - npm i -g makeshift && makeshift -r https://npm-registry.whitewater.ibm.com -s arf ibm
install:
  - npm install
script:
  - npm test
  - npm run testint
  - npm run coverage
  - npm run coverageint
  - ../deploy.sh
env:
  - secure : ""
